<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bdi_8.700.000</name>
   <tag></tag>
   <elementGuidId>2d933523-f4e0-4103-a053-ead3c91176b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>bdi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='monaPriceProduct']/div/span/span/bdi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>bdi</value>
      <webElementGuid>d29e9450-1e75-4b55-96fc-62800e02f93d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8.700.000 ₫</value>
      <webElementGuid>4ab9dbb7-ce26-4c7e-be08-b1a13e8dedf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;monaPriceProduct&quot;)/div[@class=&quot;prddt-prd-price-box detail&quot;]/span[@class=&quot;price-new&quot;]/span[@class=&quot;woocommerce-Price-amount amount&quot;]/bdi[1]</value>
      <webElementGuid>5dfc1f31-6e2c-4aa5-b355-2d794fb48d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='monaPriceProduct']/div/span/span/bdi</value>
      <webElementGuid>66fc7359-9ee6-4d5a-97ed-f0aa3e85e489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm vào yêu thích'])[1]/following::bdi[1]</value>
      <webElementGuid>57898402-f135-4756-bd82-2450527f585a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roja Parfums Apex Eau Intense'])[2]/following::bdi[1]</value>
      <webElementGuid>85844e1f-79c2-4fd8-922a-014e6fc8d90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MẪU THỬ 10ML'])[1]/preceding::bdi[1]</value>
      <webElementGuid>9f72efab-10c7-4167-a0b0-9a5e674d19a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//bdi</value>
      <webElementGuid>ea275e19-6b54-48ca-9c3a-635493c02973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//bdi[(text() = '8.700.000 ₫' or . = '8.700.000 ₫')]</value>
      <webElementGuid>837eda13-064d-41ff-be33-e56c910a94f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
