<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input Soluong</name>
   <tag></tag>
   <elementGuidId>164a7c4d-24ed-4e05-b82a-585f6f062902</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#s</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='s']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c3fb9c79-03d9-4369-a7ae-87804f160e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>monaFilterJS-input-product search-field</value>
      <webElementGuid>915515c5-c3c2-4627-9570-c608ed3380dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>5c73f4f6-4262-4910-a906-68cd38858513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tìm sản phẩm của bạn</value>
      <webElementGuid>fac646f0-6116-4013-8eb8-e7d568f12f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>49e01dbf-c160-470c-8acc-f24ea9530aa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>2138f01d-9f84-4c23-906c-db377aa019d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home page-template page-template-page-template page-template-home-template page-template-page-templatehome-template-php page page-id-42 wp-custom-logo mobile-detect theme-monatheme woo-variation-swatches wvs-behavior-blur wvs-theme-monatheme wvs-mobile wvs-show-label wvs-tooltip windows&quot;]/header[@class=&quot;header hd-repon&quot;]/div[@class=&quot;header-inner&quot;]/div[@class=&quot;hd-mid&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;hd-mid-inner&quot;]/div[@class=&quot;hd-mid-right&quot;]/form[@id=&quot;searchform&quot;]/div[@class=&quot;box-search boxSearch&quot;]/input[@id=&quot;s&quot;]</value>
      <webElementGuid>ef97b57e-8646-4b94-b496-70a81049ff39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='s']</value>
      <webElementGuid>19ca9ed5-102b-460d-a49d-a2ef01d12401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='searchform']/div/input</value>
      <webElementGuid>c0f1d98a-8d37-4259-a99b-6f403b4aaba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>57dc7004-688a-4f4f-b61f-f73d0d37bab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Tìm sản phẩm của bạn' and @name = 's' and @id = 's']</value>
      <webElementGuid>6bcad45f-6041-4570-a6bd-89b5355dff45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
