<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sa_shipping-first_name</name>
   <tag></tag>
   <elementGuidId>b818ba77-8d40-4f37-aefd-9de5017d7083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#shipping-first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='shipping-first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18b526da-0ff4-4111-bc4e-d8e921c82052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ab1c23f1-7db0-45b9-918b-b8c10de5f003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>shipping-first_name</value>
      <webElementGuid>24c028e0-ef91-4015-a451-aafe6f8bb0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>sentences</value>
      <webElementGuid>1c0b8865-2d98-4251-8b30-18ecd205b59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
      <webElementGuid>0c178f56-fe99-4b19-8b2e-951de19d4a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tên</value>
      <webElementGuid>c6238534-5b57-4f8b-bbbc-4c50067a138b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4c3cf736-870e-4015-9620-4a128eebcccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shipping-first_name&quot;)</value>
      <webElementGuid>a1e2ddfb-dd35-400d-80e6-8c6e66923770</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='shipping-first_name']</value>
      <webElementGuid>341ba37a-a55c-49dd-8741-e1c11349f15c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping']/div/input</value>
      <webElementGuid>eff6ee6f-1135-4053-8559-e4dd473454b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>c8373f13-5bc1-4388-93c6-13c8473255e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'shipping-first_name']</value>
      <webElementGuid>85fcb851-649f-47a7-9235-3e043385c703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
