<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Chuyn khon ngn hng_radio-control-wc-p_b4fe05</name>
   <tag></tag>
   <elementGuidId>8a4e9216-553b-42c3-9398-8b5247d57a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radio-control-wc-payment-method-options-cod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radio-control-wc-payment-method-options-cod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68039771-a305-4958-8e6d-85d4231c9c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio-control-wc-payment-method-options-cod</value>
      <webElementGuid>8fd439c4-6088-4df8-b324-6aadcaa1bcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wc-block-components-radio-control__input</value>
      <webElementGuid>9f759be4-72c3-4031-98b3-2d147ea5ec56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9975fd55-f6a7-40c9-b40b-52b5c0005b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio-control-wc-payment-method-options</value>
      <webElementGuid>7b74bd3b-57f3-4780-aa52-d4cca81b687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radio-control-wc-payment-method-options-cod__label</value>
      <webElementGuid>466ccfbe-2c70-4230-8242-ecf6a6cc915b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cod</value>
      <webElementGuid>56d25c39-4432-4340-8d62-e9b8d1a4b031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-control-wc-payment-method-options-cod&quot;)</value>
      <webElementGuid>bb4b54d7-efb0-4934-a9df-4d4654e6a142</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radio-control-wc-payment-method-options-cod']</value>
      <webElementGuid>e3e9de38-7aff-46fd-96fe-aa508e4454b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='payment-method']/div[2]/div/div[3]/div[2]/label/input</value>
      <webElementGuid>ee5bbce4-ddf3-4638-99d5-46efbbe4ea18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/input</value>
      <webElementGuid>caccff2e-7c41-43fd-a8d2-714f6980881e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radio-control-wc-payment-method-options-cod' and @type = 'radio' and @name = 'radio-control-wc-payment-method-options']</value>
      <webElementGuid>58be7b9d-b996-451d-b1b6-a53cf7222189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
