<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tr tin mt khi giao hng_checkbox-control-0</name>
   <tag></tag>
   <elementGuidId>10d97ae6-07fe-4afd-b886-d42ec53316bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#checkbox-control-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='checkbox-control-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75e34f66-bc8d-4bba-8a80-69d07801545e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox-control-0</value>
      <webElementGuid>12bbc9ac-a940-4b98-8187-2d3d5070813e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wc-block-components-checkbox__input</value>
      <webElementGuid>fd7e1b33-e7ee-46cb-ac41-9ceb2fbb3ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bc178f03-6773-4115-a462-29b4a3a7cc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3356fc05-4534-4c38-bebd-f344ad8d9a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkbox-control-0&quot;)</value>
      <webElementGuid>f32d231e-36f4-4a3f-908f-d0f0991856a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='checkbox-control-0']</value>
      <webElementGuid>8480b95d-3ed9-44ad-af62-2bbdb918a46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-notes']/div/div/div/div/label/input</value>
      <webElementGuid>4b488c5f-f2cc-486d-b364-b78b025d0d94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/label/input</value>
      <webElementGuid>c9906cfc-6fe6-4a0e-bbd6-aa728f3cd293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'checkbox-control-0' and @type = 'checkbox']</value>
      <webElementGuid>119f4fcf-9e2c-4f21-9531-9336b7b8bbbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
