<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Quc giaKhu vc_components-form-token-input-0</name>
   <tag></tag>
   <elementGuidId>f311464b-2e1a-4f41-b5c6-7c9506cdd517</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#components-form-token-input-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='components-form-token-input-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9f36bf4-5fd6-47d1-b74a-40ae14ab67c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>components-form-token-input-0</value>
      <webElementGuid>6d8e0a68-239f-4074-b88f-d67caaeb806c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92b706c0-e009-4386-96ee-90978f27932c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Vanuatu, Quốc gia/Khu vực</value>
      <webElementGuid>2769696e-ffa0-43ee-a11e-88feeacfccfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components-combobox-control__input components-form-token-field__input</value>
      <webElementGuid>24748e06-c497-4835-bff2-2204d2f84fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e168f7b1-1463-402a-a92d-15b8a978a99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>9f544ec1-d868-4f6a-aa21-f02532ceafe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38b2442f-2a82-41a8-986f-377fc7d280ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>f9aa621c-ed9a-418a-a43d-5ff3c67d98e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>components-form-token-suggestions-howto-0</value>
      <webElementGuid>5a68584a-271f-4c4e-8e90-de58eb41dde2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>235e2eef-db2f-49e8-8628-ee834965d77f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>components-form-token-suggestions-0</value>
      <webElementGuid>30d94c1d-d89d-4eaa-9ea2-41ef44ebc3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>79268fc5-4685-4447-adac-664004669350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;components-form-token-input-0&quot;)</value>
      <webElementGuid>21d1a665-c527-4bfe-9d10-47c92956d031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='components-form-token-input-0']</value>
      <webElementGuid>08bfa03e-2aad-48f0-87ee-98290f98f945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shipping-country']/div/div/div/div/div/div/input</value>
      <webElementGuid>31e4a72e-bad6-4f7c-94d9-868cc8e75c0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div/input</value>
      <webElementGuid>0f74f259-403d-40c5-a128-f4266695ef75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'components-form-token-input-0' and @type = 'text']</value>
      <webElementGuid>a2b8d22d-ecb6-4934-8b29-b898acd4412c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
