<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Vit Nam</name>
   <tag></tag>
   <elementGuidId>a2d2bea9-64e9-43b5-a492-0cb64a75ee9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#components-form-token-suggestions-0-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='components-form-token-suggestions-0-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>cfd18aaf-8a75-4cb0-9672-84694d61ddf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>components-form-token-suggestions-0-0</value>
      <webElementGuid>154758a4-731c-4a61-a6c6-59c56ca6cb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>f6d73fbd-82b0-48b2-be5a-e3ec5dbe1ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>components-form-token-field__suggestion is-selected</value>
      <webElementGuid>e1fe733c-eb11-4204-9a79-e988bd25568e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e519c8d3-fdb2-436a-b14b-5550b26b6b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Việt Nam</value>
      <webElementGuid>70aa70b3-682b-4372-a86b-4d8d96015c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;components-form-token-suggestions-0-0&quot;)</value>
      <webElementGuid>d855554c-70a9-4442-b7af-bce4ea6d84c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='components-form-token-suggestions-0-0']</value>
      <webElementGuid>1c1545a5-f05f-4c3c-88c1-5ba8008a8e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='components-form-token-suggestions-0']/li</value>
      <webElementGuid>60cc42c7-22a6-4dd9-820c-93285bcbcdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quốc gia/Khu vực'])[1]/following::li[1]</value>
      <webElementGuid>d290e3be-645c-431d-acdf-e136c453ed02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Căn hộ, số nhà... (không bắt buộc)'])[1]/following::li[1]</value>
      <webElementGuid>99b622f5-9d6f-48a9-a403-25d06a7f10eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mã bưu điện (không bắt buộc)'])[1]/preceding::li[1]</value>
      <webElementGuid>5e744a4e-d8e9-4910-8cee-5221976d1656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div/div/ul/li</value>
      <webElementGuid>65d5ce8d-8cc0-439e-bdc7-b3da8d0adeaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'components-form-token-suggestions-0-0' and (text() = 'Việt Nam' or . = 'Việt Nam')]</value>
      <webElementGuid>f4f0023a-28ed-4532-99f5-fae5dc0d900c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
