<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_em ang lm test, mong anh ch thng c_24bd0d</name>
   <tag></tag>
   <elementGuidId>fb7b6ad8-eeb7-4486-8b76-a335f2c12694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.wc-block-components-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='order-notes']/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b04abeb1-2943-4bf6-a180-799d15f24644</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wc-block-components-textarea</value>
      <webElementGuid>0e670cd2-2bce-4f4e-9e89-153e3a698a87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ghi chú về đơn hàng, ví dụ: thời gian hay chỉ dẫn địa điểm giao hàng chi tiết hơn.</value>
      <webElementGuid>2fa0d158-2e5e-4903-a93a-30b052ac27a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e42b61b0-8ec1-4c1e-918a-063740cfecc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>5c3bcc57-26ac-41f8-8415-f7f0ce161a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>em đang làm test, mong anh chị thông cảm không giao hàng cho em ạ. Em cảm ơn ạ.</value>
      <webElementGuid>d6fdc7fe-fb32-4c03-a653-96b4b35885c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-notes&quot;)/div[@class=&quot;wc-block-components-checkout-step__container&quot;]/div[@class=&quot;wc-block-components-checkout-step__content&quot;]/div[@class=&quot;wc-block-checkout__add-note&quot;]/textarea[@class=&quot;wc-block-components-textarea&quot;]</value>
      <webElementGuid>53c03ebf-0c10-48a9-ac4f-a084ab0b9d70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='order-notes']/div/div/div/textarea</value>
      <webElementGuid>78b0f5d2-fde9-4692-a9eb-19cea7af50fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm ghi chú cho đơn hàng của bạn'])[1]/following::textarea[1]</value>
      <webElementGuid>948bd30f-05ec-4929-b7a7-c89fa1e81e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trả tiền mặt khi giao hàng'])[1]/following::textarea[1]</value>
      <webElementGuid>019a93e9-5e5c-4b16-ba76-335ec3f34475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quay lại giỏ hàng'])[1]/preceding::textarea[1]</value>
      <webElementGuid>d6f42bf7-4daf-498e-8496-07b07ab0b110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặt hàng'])[1]/preceding::textarea[1]</value>
      <webElementGuid>23a0ea26-658a-49b6-87ad-f21aca5ef0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='em đang làm test, mong anh chị thông cảm không giao hàng cho em ạ. Em cảm ơn ạ.']/parent::*</value>
      <webElementGuid>0f14b5b3-2067-49b5-b3b0-2e568c1e8342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>563823a9-b4ee-4f08-8904-d7132ed4a625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@placeholder = 'Ghi chú về đơn hàng, ví dụ: thời gian hay chỉ dẫn địa điểm giao hàng chi tiết hơn.' and (text() = 'em đang làm test, mong anh chị thông cảm không giao hàng cho em ạ. Em cảm ơn ạ.' or . = 'em đang làm test, mong anh chị thông cảm không giao hàng cho em ạ. Em cảm ơn ạ.')]</value>
      <webElementGuid>6044c78c-fada-46c4-8b04-6413383a80b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
