<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_user_name</name>
   <tag></tag>
   <elementGuidId>c178bf28-0a7d-43d9-b35c-35ab915bdeb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user_name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9eba0726-e964-4cb4-9e63-03a678b4746a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_name</value>
      <webElementGuid>4eb520fb-8045-4b8f-ab5e-0c6b90b5669f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15c60e1b-429f-4f4b-963b-ec70e54e2352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>1948f967-778b-46c0-84fa-10983cc9e972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-login-template page-template-login-template-php page page-id-486 wp-custom-logo desktop-detect theme-monatheme woo-variation-swatches wvs-behavior-blur wvs-theme-monatheme wvs-show-label wvs-tooltip windows&quot;]/form[@id=&quot;mona-login-form&quot;]/main[@class=&quot;main spc-hd spc-hd-2 spc-hd-3 spc-hd-4&quot;]/section[@class=&quot;login&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;inner&quot;]/div[@class=&quot;login-form&quot;]/div[@class=&quot;box-form&quot;]/div[@class=&quot;group-form&quot;]/input[1]</value>
      <webElementGuid>123978e4-ba3e-47c6-b4f5-2c46c90dead7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user_name']</value>
      <webElementGuid>eee5e09c-bb50-4a22-89cd-c31fb79d8ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mona-login-form']/main/section[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>79ac079d-ba9e-42f9-983c-cf402ba40253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2d2680b8-5d0e-4ec8-a7ba-e51bddcf4eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'user_name' and @type = 'text' and @placeholder = 'Email']</value>
      <webElementGuid>a6cb0f42-007a-42fc-9ab6-5049ca5924c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
