<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu_user_pass</name>
   <tag></tag>
   <elementGuidId>e5e8adf1-0652-4511-bf04-f5eb7f739faa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;user_pass&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='user_pass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3befc6ab-08f4-4449-af88-8f9869b1e106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>re-input</value>
      <webElementGuid>2f5e6ead-5091-4c6d-84f6-e40953219956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>user_pass</value>
      <webElementGuid>b97c12f5-e34d-4609-820b-432d9925653f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>b9ee7839-416e-4851-b3d4-34ad7f2be7ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>a832c4c8-9e75-42bb-8f45-63ea19080394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-login-template page-template-login-template-php page page-id-486 wp-custom-logo desktop-detect theme-monatheme woo-variation-swatches wvs-behavior-blur wvs-theme-monatheme wvs-show-label wvs-tooltip windows&quot;]/form[@id=&quot;mona-login-form&quot;]/main[@class=&quot;main spc-hd spc-hd-2 spc-hd-3 spc-hd-4&quot;]/section[@class=&quot;login&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;inner&quot;]/div[@class=&quot;login-form&quot;]/div[@class=&quot;box-form&quot;]/div[@class=&quot;group-form&quot;]/input[@class=&quot;re-input&quot;]</value>
      <webElementGuid>044b62f3-c34d-4b1c-a58b-6babdab519dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='user_pass']</value>
      <webElementGuid>c38b4e7f-dcaa-43f2-89d0-d7375d8c5016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mona-login-form']/main/section[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>0e7d5006-f845-4cde-ad3b-1f8ae059139b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>916e7770-86f6-4016-a071-57e310180f9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'user_pass' and @type = 'password' and @placeholder = 'Mật khẩu']</value>
      <webElementGuid>d49a50db-0f60-48de-81c3-fb9ef1c15ca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
