<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_register_email</name>
   <tag></tag>
   <elementGuidId>010fc8ae-4b87-4577-805f-5fb98935a42c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;register_email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='register_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>137610d9-27de-485d-a03d-9c8e08c2668a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>63b2c789-b539-4622-bce7-e722bd0a9ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>register_email</value>
      <webElementGuid>050333ea-e660-49e9-acfe-8ef9c37df91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>033b13ea-9c13-4fa9-ab74-8b790200d4c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-register-template page-template-register-template-php page page-id-488 wp-custom-logo mobile-detect theme-monatheme woo-variation-swatches wvs-behavior-blur wvs-theme-monatheme wvs-mobile wvs-show-label wvs-tooltip windows&quot;]/form[@id=&quot;mona-register-popup&quot;]/main[@class=&quot;main spc-hd spc-hd-2 spc-hd-3 spc-hd-4&quot;]/section[@class=&quot;login&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;inner&quot;]/div[@class=&quot;login-form&quot;]/div[@class=&quot;box-form&quot;]/div[@class=&quot;group-form&quot;]/input[1]</value>
      <webElementGuid>9f02180a-d3be-44bd-be02-607b8ebce181</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='register_email']</value>
      <webElementGuid>b91b9910-46bb-41b2-9d5c-b2a86d88ced6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mona-register-popup']/main/section[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>27dde5e7-d7c4-4ed9-b6b8-6a48b9f80a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>36cdf8ff-564e-4064-863e-5a4c055a2951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'register_email' and @placeholder = 'Email']</value>
      <webElementGuid>51c997bf-c74b-4930-ad8e-c7ae17a6403a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
