<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mt khu_register_pass</name>
   <tag></tag>
   <elementGuidId>c70bc146-4f36-4bda-86a1-3999453f2840</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;register_pass&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='register_pass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ee6b510-3cb5-44ba-97aa-c090a861fb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>3466d308-f7ee-4e5c-8107-20bcccff874c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>register_pass</value>
      <webElementGuid>10d8f195-9877-424e-baf5-a785aac014a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mật khẩu</value>
      <webElementGuid>e12fc569-7b94-47c7-a2fb-4819f7f39e2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-register-template page-template-register-template-php page page-id-488 wp-custom-logo mobile-detect theme-monatheme woo-variation-swatches wvs-behavior-blur wvs-theme-monatheme wvs-mobile wvs-show-label wvs-tooltip windows&quot;]/form[@id=&quot;mona-register-popup&quot;]/main[@class=&quot;main spc-hd spc-hd-2 spc-hd-3 spc-hd-4&quot;]/section[@class=&quot;login&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;inner&quot;]/div[@class=&quot;login-form&quot;]/div[@class=&quot;box-form&quot;]/div[@class=&quot;group-form&quot;]/input[1]</value>
      <webElementGuid>56b07fd0-4157-4aef-aaaf-bd1c23348c46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='register_pass']</value>
      <webElementGuid>0990389d-9689-4b00-81ed-b10cdbf175e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mona-register-popup']/main/section[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>ae0df126-dedc-47b8-af60-2edda3ad84fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>5efccd80-f3f1-41aa-867b-9ae0e66f9534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'register_pass' and @placeholder = 'Mật khẩu']</value>
      <webElementGuid>a98283c5-57f1-49ff-b610-36a2f0672317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
