<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nhp li mt khu_register_repass</name>
   <tag></tag>
   <elementGuidId>f9f5ef50-ff33-4e78-b01d-cedbff7cde61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;register_repass&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='register_repass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c9f67fd0-6c7e-4246-b4d1-a3d00ada82fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>95c35344-a10f-4be9-8536-080ad2ee16d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>register_repass</value>
      <webElementGuid>bcc60d88-d2d0-460f-80b9-2fd261f90ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập lại mật khẩu</value>
      <webElementGuid>2f3d3110-8236-4e7b-b9a8-bb9c4a204057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-template page-template-register-template page-template-register-template-php page page-id-488 wp-custom-logo mobile-detect theme-monatheme woo-variation-swatches wvs-behavior-blur wvs-theme-monatheme wvs-mobile wvs-show-label wvs-tooltip windows&quot;]/form[@id=&quot;mona-register-popup&quot;]/main[@class=&quot;main spc-hd spc-hd-2 spc-hd-3 spc-hd-4&quot;]/section[@class=&quot;login&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;inner&quot;]/div[@class=&quot;login-form&quot;]/div[@class=&quot;box-form&quot;]/div[@class=&quot;group-form&quot;]/input[1]</value>
      <webElementGuid>c664459d-7f4f-4c2b-8182-942a9a2c262f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='register_repass']</value>
      <webElementGuid>78ba1cdc-ced3-4755-a9c2-710e57aceec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='mona-register-popup']/main/section[2]/div/div/div/div[2]/div[3]/input</value>
      <webElementGuid>586b9bad-77dc-48ec-8f3d-be81f2cdc28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>e5e2cd15-efca-448e-b453-a9a5a0fa31f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'register_repass' and @placeholder = 'Nhập lại mật khẩu']</value>
      <webElementGuid>aa905bdc-98a3-4697-98b0-fb80034bb087</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
